### ISSUE TITLE
Fußleiste anpassen

### ISSUE THREAD

**Issue by LukasMin** [Die-KoMa/die-koma.org#69]
Sobald die neue Struktur eingebaut wurde und der Kontaktlink in der Fußleiste ist, sollte dafür gesorgt werden, dass die Fußleiste dauerhaft angezeigt wird und nicht nur, wenn man ganz nach unten scrollt.

Für mobile Nutzer müsste dies eventuell anders angepasst werden.

**Comment by Grarie** [comment]
Das Issue ist jetzt schon etwas älter. Ich verstehe nicht ganz, warum das essentiell ist, dass die Fußleiste immer angezeigt wird. Ich dachte, die soll absichtlich ganz unten sein.

**Comment by LukasMino** [comment]
Das war ewig her. Ich weiß gar nicht mehr was und wieso ich hier genau meinte. Muss erstmal schauen, ob ich noch Zugriff aufs alte Konto habe.
