### ISSUE TITLE
Die neue Struktur des Menüs muss eingearbeitet werden

### ISSUE THREAD

**Issue by LukasMin** [Die-KoMa/die-koma.org#73]
Beini soll das neue Menü einpflegen, wie es im AK besprohen wurde und wie es im Pad dazu zu finden ist.
Wenn möglich soll die zukünftige Änderung dieser einfacher gestaltet werden, da es bisher sehr unübersichtlich ist.

**Comment by mmarx** [comment]
A fix has already been started.
