### ISSUE TITLE
Neu gebaute Container sollten dem Browser Cache signalisieren Assets neu zu laden

### ISSUE THREAD

**Issue by thelegy** [Die-KoMa/die-koma.org#76]
Am einfachsten wäre das, wenn man beim erneuten Bauen an die Aufrufe von Assets einen get-parameter dran hängt. Diese sollte bei jedem neuen Bauen des Containers neu generiert werden und sich nicht wiederholen.

**Comment by thelegy** [comment]
Noch mal für @imntl:

An den Stellen, an denen Assets, wie z.B. css Dateien, wie `/core/css/main.css` eingebunden werden, binden wir sie jetzt mit `/core/css/main.css?bdate=<builddate>` ein, wobei wir `<builddate>` bei jedem Bauvorgang durch einen aktuellen Timestamp des Bauvorgangs ersetzen.

Dies hat zur Folge, dass jedes mal, wenn die Assets mit einem neuen bdate Parameter eingebunden werden, der Browser diese Anfrage nicht mehr aus seinem Cache beantworten kann (weil sieht ja anders aus) und die Assets dadurch erneut angefragt werden und man so einen konsistenten Zustand erhält.

**Comment by mmarx** [comment]
Da das ja jetzt kein Container mehr ist, ist das vermutlich hinfaellig.
