### ISSUE TITLE
Header-Bild

### ISSUE THREAD

**Issue by sorachan** [Die-KoMa/die-koma.org#79]
Das aktuelle header image hat eine feste Aussparung (andere Helligkeit) für das Logo aus dem statischen Design. Für das neue responsive design sollte ein Bild ohne diese Anpassung verwendet werden.

**Comment by thelegy** [comment]
Das aktuelle Bild existiert nach meinem Wissen nur mit der Aussparung. Ursprünglich war auch das KoMa-Logo Teil des Bildes und wurde daraus Retuschiert. Es müsste also ein neues Bild gefunden werden.

**Comment by mmarx** [comment]
Mit dem Angriff „Neues Design“ kommt das alles in Ordnung.
