### ISSUE TITLE
Link von der KoMa Website zu diesem Repo

### ISSUE THREAD

**Issue by thelegy** [Die-KoMa/die-koma.org#80]
Ich fände es gut, wenn die KoMa Homepage an irgendeiner Stelle eine Referenz zu diesem Repo haben würde. Sodass $Leute, die $Dinge bearbeiten/korrigieren wollen, eine einfache Möglichkeit dafür erhalten.

**Comment by Y0nj** [comment]
Unter welchem Bereich hättest du dass denn gerne ? 
Impressum ?

**Comment by thelegy** [comment]
Footer? Wenn jemand eine Änderung hat, will ich nicht, dass die Hürde zu groß wird.

**Comment by Y0nj** [comment]
Is ne gut Idee eigentlich aber dann muss man das vernünftig kommunizieren? 
konkrete Formulierungsvorschläge

**Comment by maephju** [comment]
Neben Impressum und Datenschutz nen Punkt "Troubleshooting" zu ner Seite, wo das Vorgehen erklärt wird. Den Link zum Repo dann auf der Seite.

**Comment by Y0nj** [comment]
Klingt gut :+1:

**Comment by thelegy** [comment]
Alternativ direkt einen Link zum erstellen eines Issues und dann sinnvolle Github Issue Templates bauen?
